### ISSUE TITLE
Collaboration on adding new profiles?

### ISSUE THREAD

**Issue by sideshowbarker** [shuyo/language-detection#84]
I’m wondering if you’re still willing to accept PRs to the`com.cybozu.labs.langdetect` sources for more language profiles, and to do new releases of the library.

I ask because for an integration of the `com.cybozu.labs.langdetect` code in a project I work on, there are a number of languages I anticipate a need to consider adding but I see that in #76 there is an open request from more than one year ago to add Welsh support and in #81 there appears to be an umerged patch for adding Esperanto from 7 months ago.

As far as the actual project where I have a need for more languages, I work for the W3C and maintain the [W3C HTML Checker](https://validator.w3.org/nu/) and recently added a new feature using the `com.cybozu.labs.langdetect` code to attempt to detect the language of all HTML documents it checks and then to do things like report a warning if it finds that the `<html lang="foo">` value differs from the detected language.

The core code is in the [nu.validator.servlet.LanguageDetectingXMLReaderWrapper](https://github.com/validator/validator/blob/master/src/nu/validator/servlet/LanguageDetectingXMLReaderWrapper.java) class in the HTML checker sources, if you’re curious to see how it’s being used.

Thus far in work on that I have identified a possible need to add support for Armenian and Georgian, but I anticipate that for the HTML Checker we might want to add quite a lot more.

If to get PRs for new profiles merged it would help to have somebody testing them to make sure they work as expected, I’d be very willing to put time into that—along with prioritizing which additional languages to focus on getting tested and added to master. I would also be wiling to help with building new releases, including doing releases for maven to the central repository (which I already do for the HTML checker code itself).

So I am hoping to hear back about what kind of collaboration on that might be possible, and what kind of workflow would be best. In the mean time I will likely be opening up some new PRs soon with patches for additional language profiles, so alternatively we could just deal with those case by case and see what kind of collaboration process naturally emerges from that.

**Comment by sideshowbarker** [comment]
Closing this because I have since realized that I can just add new profiles in my own source rather than needing them to be added upstream. Sorry for the noise about this.

**Comment by dansupriti** [comment]
Hi sideshowbarker ,
Could you please help me with the steps how to add new language profile in my own sources?

**Comment by grischard** [comment]
Hi @dansupriti, I've blogged about the steps here: https://stereo.lu/detecting-luxembourgish-using-a-spam-filter-and-wikipedia

**Comment by dansupriti** [comment]
Hi @grischard ..Thanks for sharing the link of your blog, it's really helpful for me.
